import type { Scenario, SkillId } from '../domain/types'

export const scenarios: Scenario[] = [
  {
    id: 'foundations-daily-rate',
    skillId: 'foundations',
    title: 'The daily pulse',
    eyebrow: 'Telemetry · warm-up',
    prompt: 'A fleet emits 240 million health events each day. Use 100,000 seconds per day.',
    question: 'What is the approximate average event rate?',
    assumptions: ['Events are spread evenly', 'A day is rounded to 100,000 seconds'],
    formulaChoices: [
      { id: 'divide-day', label: 'Daily events ÷ seconds per day' },
      { id: 'multiply-day', label: 'Daily events × seconds per day' },
      { id: 'divide-users', label: 'Seconds per day ÷ daily events' },
    ],
    correctFormulaId: 'divide-day',
    answer: { baseValue: 2_400, dimension: 'rate', displayValue: 2_400, displayUnit: 'rps', tolerance: 0.25 },
    implicationChoices: [
      { id: 'small-steady', label: 'The average is only a few thousand events/s; bursts may dominate sizing.' },
      { id: 'millions', label: 'The service needs capacity for hundreds of millions of events/s.' },
      { id: 'storage-only', label: 'Request rate does not matter for this workload.' },
    ],
    correctImplicationId: 'small-steady',
    mentalModel: '240M ÷ 100K → cancel five zeros → 2.4K.',
    hint: 'Dividing by 100,000 is the same as moving the decimal point five places left.',
    walkthrough: ['240 million = 2.4 × 10⁸', '100,000 seconds = 10⁵', '2.4 × 10⁸ ÷ 10⁵ = 2.4 × 10³ = 2,400 events/s'],
  },
  {
    id: 'foundations-bits-bytes',
    skillId: 'foundations',
    title: 'Bytes onto the wire',
    eyebrow: 'Networking · unit check',
    prompt: 'A worker sends 8 MB of data every second. Network capacity is quoted in bits per second.',
    question: 'What network rate does that represent?',
    assumptions: ['Use decimal MB', 'There are 8 bits in a byte'],
    formulaChoices: [
      { id: 'times-eight', label: 'MB/second × 8 bits/byte' },
      { id: 'divide-eight', label: 'MB/second ÷ 8 bits/byte' },
      { id: 'times-thousand', label: 'MB/second × 1,000 seconds' },
    ],
    correctFormulaId: 'times-eight',
    answer: { baseValue: 64_000_000, dimension: 'bandwidth', displayValue: 64, displayUnit: 'Mbps', tolerance: 0.05 },
    implicationChoices: [
      { id: 'hundred-mbps', label: 'A 100 Mbps link has some headroom; a 10 Mbps link does not.' },
      { id: 'one-mbps', label: 'A 1 Mbps link is comfortably sufficient.' },
      { id: 'disk', label: 'Only disk capacity needs to change.' },
    ],
    correctImplicationId: 'hundred-mbps',
    mentalModel: 'The prefixes stay aligned: 8 megabytes × 8 = 64 megabits.',
    hint: 'Network rates use bits. Data sizes commonly use bytes.',
    walkthrough: ['8 MB/s × 8 bits/byte = 64 Mb/s', '64 Mb/s is written as 64 Mbps', 'The answer is a rate, not a stored-data quantity'],
  },
  {
    id: 'foundations-object-size',
    skillId: 'foundations',
    title: 'A million small files',
    eyebrow: 'Storage · powers of ten',
    prompt: 'Three million generated previews average 500 KB each.',
    question: 'Roughly how much raw data is that?',
    assumptions: ['Use decimal units', 'Ignore filesystem and metadata overhead'],
    formulaChoices: [
      { id: 'count-times-size', label: 'Object count × average object size' },
      { id: 'count-divide-size', label: 'Object count ÷ average object size' },
      { id: 'size-times-time', label: 'Average object size × seconds per day' },
    ],
    correctFormulaId: 'count-times-size',
    answer: { baseValue: 1_500_000_000_000, dimension: 'data', displayValue: 1.5, displayUnit: 'TB', tolerance: 0.1 },
    implicationChoices: [
      { id: 'few-tb', label: 'The raw set is a few terabytes, before replicas and indexes.' },
      { id: 'few-mb', label: 'The complete set fits comfortably in a few megabytes.' },
      { id: 'bandwidth-result', label: 'The result tells us the required network rate.' },
    ],
    correctImplicationId: 'few-tb',
    mentalModel: '3M × 500K bytes = 1,500 × 10⁹ bytes = 1.5 TB.',
    hint: 'Multiply the leading numbers, then add the powers of ten.',
    walkthrough: ['3 million = 3 × 10⁶', '500 KB = 5 × 10⁵ bytes', '3 × 5 × 10¹¹ = 1.5 × 10¹² bytes = 1.5 TB'],
  },
  {
    id: 'foundations-orders',
    skillId: 'foundations',
    title: 'Fan-out objects',
    eyebrow: 'Feeds · magnitude',
    prompt: 'Two hundred million users each have five precomputed feed objects.',
    question: 'How many feed objects exist?',
    assumptions: ['Every user has exactly five current objects'],
    formulaChoices: [
      { id: 'users-times-items', label: 'Users × objects per user' },
      { id: 'users-divide-items', label: 'Users ÷ objects per user' },
      { id: 'items-times-seconds', label: 'Objects per user × seconds per day' },
    ],
    correctFormulaId: 'users-times-items',
    answer: { baseValue: 1_000_000_000, dimension: 'quantity', displayValue: 1, displayUnit: 'billion', tolerance: 0.01 },
    implicationChoices: [
      { id: 'billion-records', label: 'Even tiny per-object metadata becomes material across a billion objects.' },
      { id: 'five-records', label: 'Only five records need to be stored globally.' },
      { id: 'latency-only', label: 'The count only establishes request latency.' },
    ],
    correctImplicationId: 'billion-records',
    mentalModel: '200 million × 5 = 1,000 million = 1 billion.',
    hint: 'You can keep the “million” unit while multiplying 200 × 5.',
    walkthrough: ['200M users × 5 objects/user = 1,000M objects', '1,000 million = 1 billion', 'Units cancel to objects'],
  },
  {
    id: 'load-post-writes',
    skillId: 'load',
    title: 'Posts arrive all day',
    eyebrow: 'Social · writes',
    prompt: '100 million daily active users each publish 10 posts. Use 100,000 seconds per day.',
    question: 'Estimate the average write rate.',
    assumptions: ['Activity is averaged across the day', 'One post creates one write request'],
    formulaChoices: [
      { id: 'users-actions-over-time', label: 'Users × posts/user ÷ seconds/day' },
      { id: 'users-over-actions-time', label: 'Users ÷ posts/user × seconds/day' },
      { id: 'users-actions-time', label: 'Users × posts/user × seconds/day' },
    ],
    correctFormulaId: 'users-actions-over-time',
    answer: { baseValue: 10_000, dimension: 'rate', displayValue: 10_000, displayUnit: 'rps', tolerance: 0.2 },
    implicationChoices: [
      { id: 'apply-peak', label: 'Use this as a baseline, then apply a peak factor before provisioning.' },
      { id: 'exact-peak', label: 'This average is automatically the maximum traffic.' },
      { id: 'one-server', label: 'The estimate proves one server is sufficient.' },
    ],
    correctImplicationId: 'apply-peak',
    mentalModel: '100M × 10 = 1B/day; 1B ÷ 100K = 10K/s.',
    hint: 'First find daily writes. Only then convert the time unit.',
    walkthrough: ['100M × 10 = 1B posts/day', '1B ÷ 100K seconds ≈ 10K writes/s', 'The exact daily average is about 11.6K writes/s'],
  },
  {
    id: 'load-peak-reads',
    skillId: 'load',
    title: 'The evening feed peak',
    eyebrow: 'News feed · reads',
    prompt: '50 million users make 20 feed reads per day. Peak traffic is 3× the daily average.',
    question: 'Estimate peak read RPS using 100,000 seconds/day.',
    assumptions: ['All 20 actions are reads', 'Peak multiplier is applied after averaging'],
    formulaChoices: [
      { id: 'daily-over-time-peak', label: 'Users × reads/user ÷ seconds/day × peak factor' },
      { id: 'daily-over-peak', label: 'Users × reads/user ÷ peak factor' },
      { id: 'peak-over-daily', label: 'Peak factor ÷ users ÷ seconds/day' },
    ],
    correctFormulaId: 'daily-over-time-peak',
    answer: { baseValue: 30_000, dimension: 'rate', displayValue: 30_000, displayUnit: 'rps', tolerance: 0.2 },
    implicationChoices: [
      { id: 'size-thirty-k', label: 'The read path should sustain roughly 30K RPS before further safety margin.' },
      { id: 'size-ten-k', label: 'Provisioning for the 10K average fully covers the stated peak.' },
      { id: 'storage-three', label: 'Storage must be tripled, but request capacity is unchanged.' },
    ],
    correctImplicationId: 'size-thirty-k',
    mentalModel: '50M × 20 = 1B/day → 10K average → 30K peak.',
    hint: 'Keep average and peak as separate named steps.',
    walkthrough: ['50M × 20 = 1B reads/day', '1B ÷ 100K ≈ 10K average RPS', '10K × 3 = 30K peak RPS'],
  },
  {
    id: 'load-device-heartbeats',
    skillId: 'load',
    title: 'Heartbeat traffic',
    eyebrow: 'IoT · periodic load',
    prompt: 'Two million connected devices send one heartbeat every 30 seconds.',
    question: 'What steady request rate does this create?',
    assumptions: ['Heartbeats are evenly staggered', 'Each heartbeat is one request'],
    formulaChoices: [
      { id: 'devices-over-interval', label: 'Connected devices ÷ heartbeat interval' },
      { id: 'devices-times-interval', label: 'Connected devices × heartbeat interval' },
      { id: 'interval-over-devices', label: 'Heartbeat interval ÷ connected devices' },
    ],
    correctFormulaId: 'devices-over-interval',
    answer: { baseValue: 66_667, dimension: 'rate', displayValue: 67_000, displayUnit: 'rps', tolerance: 0.15 },
    implicationChoices: [
      { id: 'stagger', label: 'Clock synchronisation could create bursts far above this staggered average.' },
      { id: 'daily-only', label: 'The interval has no effect on request rate.' },
      { id: 'thirty-rps', label: 'The system only needs to handle 30 requests per second.' },
    ],
    correctImplicationId: 'stagger',
    mentalModel: '2,000,000 ÷ 30 ≈ 2,000,000 ÷ 3 ÷ 10 ≈ 67,000.',
    hint: 'Ask how many thirtieths of the fleet report during one second.',
    walkthrough: ['2,000,000 devices ÷ 30 seconds', '2,000,000 ÷ 3 ≈ 667,000', 'Divide by another 10 → about 67,000 requests/s'],
  },
  {
    id: 'load-read-split',
    skillId: 'load',
    title: 'Read-heavy short links',
    eyebrow: 'Redirects · traffic split',
    prompt: 'A short-link service handles 600 million requests/day; 90% are redirects (reads).',
    question: 'Estimate average read RPS using 100,000 seconds/day.',
    assumptions: ['Reads are 90% of total traffic', 'Traffic is averaged across a day'],
    formulaChoices: [
      { id: 'total-share-over-time', label: 'Daily requests × read share ÷ seconds/day' },
      { id: 'total-over-share-time', label: 'Daily requests ÷ read share × seconds/day' },
      { id: 'total-minus-seconds', label: 'Daily requests − seconds/day' },
    ],
    correctFormulaId: 'total-share-over-time',
    answer: { baseValue: 5_400, dimension: 'rate', displayValue: 5_400, displayUnit: 'rps', tolerance: 0.2 },
    implicationChoices: [
      { id: 'optimise-read', label: 'Caching the read path can address most of the request volume.' },
      { id: 'write-dominant', label: 'Write capacity is the clear bottleneck from this split.' },
      { id: 'ninety-times', label: 'Read RPS is 90 times total RPS.' },
    ],
    correctImplicationId: 'optimise-read',
    mentalModel: '600M × 0.9 = 540M/day; divide by 100K → 5.4K/s.',
    hint: 'Apply the traffic share to the daily count, then convert to seconds.',
    walkthrough: ['600M × 90% = 540M read requests/day', '540M ÷ 100K ≈ 5.4K read requests/s', 'The remaining 10% is about 600 write RPS'],
  },
  {
    id: 'storage-chat-retention',
    skillId: 'storage',
    title: 'Retained chat messages',
    eyebrow: 'Messaging · retention',
    prompt: 'Ten million 1 KB messages arrive daily. Keep 30 days with three copies.',
    question: 'Estimate provisioned message storage.',
    assumptions: ['Use decimal units', 'Replication factor is three', 'Ignore indexes and attachments'],
    formulaChoices: [
      { id: 'count-size-days-replicas', label: 'Messages/day × size × days × copies' },
      { id: 'count-size-over-days', label: 'Messages/day × size ÷ days' },
      { id: 'count-over-size-copies', label: 'Messages/day ÷ size × copies' },
    ],
    correctFormulaId: 'count-size-days-replicas',
    answer: { baseValue: 900_000_000_000, dimension: 'data', displayValue: 900, displayUnit: 'GB', tolerance: 0.1 },
    implicationChoices: [
      { id: 'about-tb', label: 'Plan for roughly a terabyte before indexes and operational headroom.' },
      { id: 'ten-gb', label: 'The entire retained set is only the 10 GB written on day one.' },
      { id: 'thirty-tb', label: 'Retention alone turns each daily gigabyte into a petabyte.' },
    ],
    correctImplicationId: 'about-tb',
    mentalModel: '10M × 1KB = 10GB/day; ×30 ×3 = 900GB.',
    hint: 'Name raw data per day before applying time and replicas.',
    walkthrough: ['10M × 1 KB = 10 GB/day', '10 GB/day × 30 days = 300 GB raw retained', '300 GB × 3 copies = 900 GB provisioned'],
  },
  {
    id: 'storage-metrics',
    skillId: 'storage',
    title: 'A week of metrics',
    eyebrow: 'Observability · high volume',
    prompt: 'One million metrics/second average 200 bytes. Retain seven days without replication.',
    question: 'Estimate the retained raw data using 100,000 seconds/day.',
    assumptions: ['Use decimal units', 'Round a day to 100,000 seconds'],
    formulaChoices: [
      { id: 'rate-size-time-days', label: 'Metrics/s × bytes/metric × seconds/day × days' },
      { id: 'rate-over-size-days', label: 'Metrics/s ÷ bytes/metric × days' },
      { id: 'rate-size-over-time', label: 'Metrics/s × bytes/metric ÷ seconds/day' },
    ],
    correctFormulaId: 'rate-size-time-days',
    answer: { baseValue: 140_000_000_000_000, dimension: 'data', displayValue: 140, displayUnit: 'TB', tolerance: 0.2 },
    implicationChoices: [
      { id: 'compression-matters', label: 'Compression and downsampling could materially change a ~100 TB footprint.' },
      { id: 'fits-memory', label: 'The complete week trivially fits in a typical process heap.' },
      { id: 'rate-only', label: 'Retention length cannot affect stored volume.' },
    ],
    correctImplicationId: 'compression-matters',
    mentalModel: '1M × 200B = 200MB/s; ×100K = 20TB/day; ×7 = 140TB.',
    hint: 'Convert the per-second stream into one day, then multiply by retention.',
    walkthrough: ['1M × 200 bytes = 200 MB/s', '200 MB/s × 100K seconds ≈ 20 TB/day', '20 TB/day × 7 ≈ 140 TB'],
  },
  {
    id: 'storage-video-library',
    skillId: 'storage',
    title: 'Encoded video library',
    eyebrow: 'Media · replication',
    prompt: 'A catalogue has 50,000 encoded videos averaging 500 MB. Store three copies.',
    question: 'How much provisioned storage is required?',
    assumptions: ['500 MB includes all chosen renditions', 'Use decimal units'],
    formulaChoices: [
      { id: 'videos-size-copies', label: 'Videos × average size × copies' },
      { id: 'videos-over-size', label: 'Videos ÷ average size' },
      { id: 'size-copies-over-videos', label: 'Average size × copies ÷ videos' },
    ],
    correctFormulaId: 'videos-size-copies',
    answer: { baseValue: 75_000_000_000_000, dimension: 'data', displayValue: 75, displayUnit: 'TB', tolerance: 0.1 },
    implicationChoices: [
      { id: 'object-storage', label: 'A tens-of-terabytes object store is plausible; growth and renditions need separate allowance.' },
      { id: 'single-gb', label: 'A 1 GB disk can hold the replicated catalogue.' },
      { id: 'requests-answer', label: 'This calculation determines peak request rate.' },
    ],
    correctImplicationId: 'object-storage',
    mentalModel: '50K × 500MB = 25TB raw; ×3 = 75TB.',
    hint: 'Calculate one copy first, then apply replication.',
    walkthrough: ['50,000 × 500 MB = 25,000,000 MB', '25,000,000 MB = 25 TB raw', '25 TB × 3 copies = 75 TB'],
  },
  {
    id: 'storage-photo-day',
    skillId: 'storage',
    title: 'One day of photos',
    eyebrow: 'Photo sharing · ingestion',
    prompt: '500 million users upload two photos/day, averaging 2 MB per photo.',
    question: 'Estimate raw storage added each day.',
    assumptions: ['No replication', 'No thumbnails', 'Use decimal units'],
    formulaChoices: [
      { id: 'users-photos-size', label: 'Users × photos/user/day × size/photo' },
      { id: 'users-over-photos', label: 'Users ÷ photos/user/day ÷ size/photo' },
      { id: 'users-size-over-time', label: 'Users × size/photo ÷ seconds/day' },
    ],
    correctFormulaId: 'users-photos-size',
    answer: { baseValue: 2_000_000_000_000_000, dimension: 'data', displayValue: 2, displayUnit: 'PB', tolerance: 0.05 },
    implicationChoices: [
      { id: 'lifecycle', label: 'At petabytes per day, lifecycle policy and derived-image overhead are first-order concerns.' },
      { id: 'laptop', label: 'A laptop disk can retain years of uploads.' },
      { id: 'two-mb-total', label: 'Only 2 MB is added each day because photos share storage.' },
    ],
    correctImplicationId: 'lifecycle',
    mentalModel: '500M × 2 = 1B photos; ×2MB = 2B MB = 2PB.',
    hint: 'First determine how many photos arrive, then attach bytes to each one.',
    walkthrough: ['500M users × 2 = 1B photos/day', '1B photos × 2 MB = 2B MB/day', '1 billion MB = 1 PB, so the result is 2 PB/day'],
  },
  {
    id: 'bandwidth-video',
    skillId: 'bandwidth',
    title: 'Prime-time video',
    eyebrow: 'Streaming · egress',
    prompt: 'Two million viewers are concurrently streaming at 4 Mbps each.',
    question: 'Estimate total video egress.',
    assumptions: ['Two million is concurrent, not registered users', 'Ignore protocol overhead'],
    formulaChoices: [
      { id: 'concurrency-times-bitrate', label: 'Concurrent streams × bitrate/stream' },
      { id: 'users-over-bitrate', label: 'Concurrent streams ÷ bitrate/stream' },
      { id: 'bitrate-times-day', label: 'Bitrate/stream × seconds/day' },
    ],
    correctFormulaId: 'concurrency-times-bitrate',
    answer: { baseValue: 8_000_000_000_000, dimension: 'bandwidth', displayValue: 8, displayUnit: 'Tbps', tolerance: 0.05 },
    implicationChoices: [
      { id: 'cdn', label: 'Multi-terabit egress strongly motivates CDN distribution near viewers.' },
      { id: 'single-link', label: 'A single 1 Gbps server link can carry the complete audience.' },
      { id: 'total-users', label: 'Registered-user count should replace concurrent viewers in this equation.' },
    ],
    correctImplicationId: 'cdn',
    mentalModel: '2M × 4 Mbps = 8M Mbps = 8Tbps.',
    hint: 'Because the per-viewer rate is already in bits/s, no ×8 conversion is needed.',
    walkthrough: ['2 million simultaneous streams × 4 Mbps', '= 8 million Mbps', '1 million Mbps = 1 Tbps, so total egress is 8 Tbps'],
  },
  {
    id: 'bandwidth-api',
    skillId: 'bandwidth',
    title: 'A chunky API response',
    eyebrow: 'API · egress',
    prompt: 'An endpoint serves 20,000 responses/second, averaging 50 KB each.',
    question: 'Estimate response bandwidth in bits per second.',
    assumptions: ['Use decimal KB', 'Ignore headers and compression'],
    formulaChoices: [
      { id: 'rps-bytes-eight', label: 'Responses/s × bytes/response × 8 bits/byte' },
      { id: 'rps-over-bytes', label: 'Responses/s ÷ bytes/response' },
      { id: 'rps-bytes-over-eight', label: 'Responses/s × bytes/response ÷ 8' },
    ],
    correctFormulaId: 'rps-bytes-eight',
    answer: { baseValue: 8_000_000_000, dimension: 'bandwidth', displayValue: 8, displayUnit: 'Gbps', tolerance: 0.05 },
    implicationChoices: [
      { id: 'multiple-links', label: 'Payload compression or multiple network links may be material at about 8 Gbps.' },
      { id: 'eight-kbps', label: 'A dial-up-scale connection is sufficient.' },
      { id: 'storage-only', label: 'The result only affects retained storage.' },
    ],
    correctImplicationId: 'multiple-links',
    mentalModel: '20K × 50KB = 1GB/s; ×8 = 8Gbps.',
    hint: 'First compute bytes per second. Convert to bits only at the end.',
    walkthrough: ['20,000 × 50 KB = 1,000,000 KB/s', '1,000,000 KB/s = 1 GB/s', '1 GB/s × 8 = 8 Gbps'],
  },
  {
    id: 'bandwidth-upload',
    skillId: 'bandwidth',
    title: 'Photo upload ingress',
    eyebrow: 'Media · ingress',
    prompt: 'At peak, 5,000 photos/second arrive with an average size of 2 MB.',
    question: 'Estimate incoming bandwidth.',
    assumptions: ['Use decimal MB', 'Ignore protocol overhead'],
    formulaChoices: [
      { id: 'rate-size-eight', label: 'Uploads/s × MB/upload × 8 bits/byte' },
      { id: 'rate-over-size', label: 'Uploads/s ÷ MB/upload' },
      { id: 'size-over-rate', label: 'MB/upload ÷ uploads/s' },
    ],
    correctFormulaId: 'rate-size-eight',
    answer: { baseValue: 80_000_000_000, dimension: 'bandwidth', displayValue: 80, displayUnit: 'Gbps', tolerance: 0.05 },
    implicationChoices: [
      { id: 'distributed-ingest', label: 'Tens of Gbps suggests distributed upload endpoints and direct object-store uploads.' },
      { id: 'one-hundred-mbps', label: 'One 100 Mbps link has abundant headroom.' },
      { id: 'retention', label: 'Changing retention is the only way to handle this network rate.' },
    ],
    correctImplicationId: 'distributed-ingest',
    mentalModel: '5K × 2MB = 10GB/s; ×8 = 80Gbps.',
    hint: 'Keep ingress direction separate from downstream image-processing traffic.',
    walkthrough: ['5,000 × 2 MB = 10,000 MB/s', '10,000 MB/s = 10 GB/s', '10 GB/s × 8 = 80 Gbps'],
  },
  {
    id: 'bandwidth-audio',
    skillId: 'bandwidth',
    title: 'Live audio audience',
    eyebrow: 'Audio · concurrency',
    prompt: 'One million listeners concurrently receive 192 kbps audio streams.',
    question: 'Estimate total egress bandwidth.',
    assumptions: ['All listeners are simultaneous', 'Bitrate already includes encoding'],
    formulaChoices: [
      { id: 'listeners-times-rate', label: 'Concurrent listeners × bitrate/listener' },
      { id: 'listeners-over-rate', label: 'Concurrent listeners ÷ bitrate/listener' },
      { id: 'rate-times-eight', label: 'Bitrate/listener × 8 bits/byte' },
    ],
    correctFormulaId: 'listeners-times-rate',
    answer: { baseValue: 192_000_000_000, dimension: 'bandwidth', displayValue: 192, displayUnit: 'Gbps', tolerance: 0.05 },
    implicationChoices: [
      { id: 'edge-delivery', label: 'Hundreds of Gbps makes edge delivery and regional distribution important.' },
      { id: 'tiny-egress', label: 'Total egress remains below 1 Mbps.' },
      { id: 'multiply-eight', label: 'The stated bitrate must be multiplied by eight again.' },
    ],
    correctImplicationId: 'edge-delivery',
    mentalModel: '1M × 192 kbps = 192B bps = 192Gbps.',
    hint: 'kbps is already a bit rate—do not convert it as though it were kilobytes.',
    walkthrough: ['1 million × 192 thousand bits/s', '= 192 × 10⁹ bits/s', '= 192 Gbps'],
  },
  {
    id: 'latency-sequential',
    skillId: 'latency',
    title: 'A serial request chain',
    eyebrow: 'API · critical path',
    prompt: 'An API calls three required dependencies sequentially: 50 ms, 100 ms, and 200 ms.',
    question: 'Estimate dependency latency on the critical path.',
    assumptions: ['Calls cannot overlap', 'Ignore application overhead'],
    formulaChoices: [
      { id: 'sum-latencies', label: 'Add all required sequential latencies' },
      { id: 'max-latency', label: 'Take only the slowest dependency' },
      { id: 'average-latency', label: 'Average the three dependency latencies' },
    ],
    correctFormulaId: 'sum-latencies',
    answer: { baseValue: 350, dimension: 'latency', displayValue: 350, displayUnit: 'ms', tolerance: 0.01 },
    implicationChoices: [
      { id: 'parallelise', label: 'If independent, parallelising calls could reduce the dependency path toward 200 ms.' },
      { id: 'already-parallel', label: 'The current sequential chain already takes only 200 ms.' },
      { id: 'storage-fix', label: 'Adding storage capacity necessarily removes all latency.' },
    ],
    correctImplicationId: 'parallelise',
    mentalModel: 'Sequential waits stack: 50 + 100 + 200 = 350.',
    hint: 'Draw each dependency one after another on a timeline.',
    walkthrough: ['The second call waits for the first', 'The third waits for the second', '50 + 100 + 200 = 350 ms'],
  },
  {
    id: 'latency-parallel',
    skillId: 'latency',
    title: 'Parallel profile panels',
    eyebrow: 'Frontend API · fan-out',
    prompt: 'Three independent calls begin together and take 40 ms, 90 ms, and 150 ms. All results are required.',
    question: 'When is the parallel group complete?',
    assumptions: ['Calls start together', 'No additional coordination overhead'],
    formulaChoices: [
      { id: 'max-branch', label: 'Take the maximum required branch latency' },
      { id: 'sum-branches', label: 'Add every branch latency' },
      { id: 'min-branch', label: 'Take the fastest branch latency' },
    ],
    correctFormulaId: 'max-branch',
    answer: { baseValue: 150, dimension: 'latency', displayValue: 150, displayUnit: 'ms', tolerance: 0.01 },
    implicationChoices: [
      { id: 'slow-branch', label: 'Optimising the 150 ms branch offers the clearest critical-path improvement.' },
      { id: 'fast-branch', label: 'Only the 40 ms branch determines completion time.' },
      { id: 'sum', label: 'Users must always wait 280 ms for parallel work.' },
    ],
    correctImplicationId: 'slow-branch',
    mentalModel: 'Parallel work finishes when its slowest required branch finishes.',
    hint: 'Imagine all three timers starting at the same instant.',
    walkthrough: ['Calls overlap rather than stack', 'The 40 ms and 90 ms calls finish while the 150 ms call is still running', 'The group completes at max(40, 90, 150) = 150 ms'],
  },
  {
    id: 'latency-mixed-path',
    skillId: 'latency',
    title: 'Fan-out plus rendering',
    eyebrow: 'Aggregation · mixed path',
    prompt: 'After 20 ms of authentication, three parallel calls take 80 ms, 120 ms, and 50 ms. Rendering then takes 30 ms.',
    question: 'Estimate end-to-end latency.',
    assumptions: ['Authentication and rendering are serial', 'All parallel results are required'],
    formulaChoices: [
      { id: 'serial-max-serial', label: 'Authentication + max(parallel calls) + rendering' },
      { id: 'sum-everything', label: 'Add authentication, all calls, and rendering' },
      { id: 'max-everything', label: 'Take only the single largest number' },
    ],
    correctFormulaId: 'serial-max-serial',
    answer: { baseValue: 170, dimension: 'latency', displayValue: 170, displayUnit: 'ms', tolerance: 0.01 },
    implicationChoices: [
      { id: 'branch-dominates', label: 'The 120 ms branch dominates the fan-out, but serial work still contributes 50 ms.' },
      { id: 'render-hidden', label: 'Rendering is free because some earlier work was parallel.' },
      { id: 'sum-300', label: 'Parallelism has no effect and all five times simply stack.' },
    ],
    correctImplicationId: 'branch-dominates',
    mentalModel: '20 + max(80, 120, 50) + 30 = 170.',
    hint: 'Collapse the parallel group to one number, then add the serial stages.',
    walkthrough: ['Authentication costs 20 ms', 'Parallel fan-out costs max(80, 120, 50) = 120 ms', 'Rendering adds 30 ms: 20 + 120 + 30 = 170 ms'],
  },
  {
    id: 'latency-cache-path',
    skillId: 'latency',
    title: 'A cache-hit path',
    eyebrow: 'Read API · serial stages',
    prompt: 'A cache-hit request spends 5 ms at the edge, 8 ms in the service, 2 ms in cache, and 5 ms returning to the client.',
    question: 'Estimate end-to-end latency for this path.',
    assumptions: ['All listed stages are sequential', 'No retries or queueing'],
    formulaChoices: [
      { id: 'sum-stages', label: 'Add each sequential stage' },
      { id: 'max-stage', label: 'Use only the slowest stage' },
      { id: 'cache-only', label: 'Use only cache lookup time' },
    ],
    correctFormulaId: 'sum-stages',
    answer: { baseValue: 20, dimension: 'latency', displayValue: 20, displayUnit: 'ms', tolerance: 0.01 },
    implicationChoices: [
      { id: 'non-cache-majority', label: 'Cache lookup is only 2 ms; optimising it alone cannot remove most of the 20 ms path.' },
      { id: 'cache-all', label: 'The 2 ms cache lookup is the complete user-visible latency.' },
      { id: 'parallel-assume', label: 'All stages can be assumed to happen in parallel.' },
    ],
    correctImplicationId: 'non-cache-majority',
    mentalModel: '5 + 8 + 2 + 5 = 20 ms.',
    hint: 'A fast cache does not erase network and application time around it.',
    walkthrough: ['All four stages lie one after another', '5 + 8 + 2 + 5 = 20', 'The cache itself is only 10% of this hit path'],
  },
  {
    id: 'compute-api-raw',
    skillId: 'compute',
    title: 'CPU for a hot API',
    eyebrow: 'API · raw demand',
    prompt: 'An API handles 10,000 RPS and uses 10 ms of CPU time per request.',
    question: 'How many fully utilised CPU cores does the work consume?',
    assumptions: ['CPU time is evenly distributed', 'One core supplies 1,000 CPU-ms each second'],
    formulaChoices: [
      { id: 'rps-cpu-over-second', label: 'RPS × CPU ms/request ÷ 1,000 ms/second' },
      { id: 'rps-over-cpu', label: 'RPS ÷ CPU ms/request' },
      { id: 'cpu-times-second', label: 'CPU ms/request × 1,000 ms/second' },
    ],
    correctFormulaId: 'rps-cpu-over-second',
    answer: { baseValue: 100, dimension: 'compute', displayValue: 100, displayUnit: 'cores', tolerance: 0.01 },
    implicationChoices: [
      { id: 'add-headroom', label: '100 cores is raw demand; provision more to keep utilisation below 100%.' },
      { id: 'exact-provision', label: 'Exactly 100 cores guarantees safe peak operation.' },
      { id: 'ten-cores', label: 'Ten milliseconds always means only ten cores are needed.' },
    ],
    correctImplicationId: 'add-headroom',
    mentalModel: '10K × 10ms = 100K CPU-ms/s; divide by 1K = 100 cores.',
    hint: 'A core contains 1,000 milliseconds of CPU capacity in each second.',
    walkthrough: ['10,000 × 10 ms = 100,000 CPU-ms per second', '100,000 ÷ 1,000 = 100 CPU-seconds per second', 'That is 100 fully utilised cores'],
  },
  {
    id: 'compute-utilisation',
    skillId: 'compute',
    title: 'Leave room to breathe',
    eyebrow: 'Search · utilisation',
    prompt: 'Search traffic is 50,000 RPS at 4 ms CPU/request. Target 50% average CPU utilisation.',
    question: 'How many cores should be provisioned?',
    assumptions: ['CPU work parallelises across cores', '50% target means twice raw capacity'],
    formulaChoices: [
      { id: 'raw-over-util', label: '(RPS × CPU seconds/request) ÷ target utilisation' },
      { id: 'raw-times-util', label: 'RPS × CPU seconds/request × target utilisation' },
      { id: 'rps-over-ms', label: 'RPS ÷ CPU ms/request' },
    ],
    correctFormulaId: 'raw-over-util',
    answer: { baseValue: 400, dimension: 'compute', displayValue: 400, displayUnit: 'cores', tolerance: 0.01 },
    implicationChoices: [
      { id: 'raw-two-hundred', label: 'Raw demand is 200 cores; 400 provisioned keeps the target near 50%.' },
      { id: 'one-hundred', label: 'A lower utilisation target always reduces provisioned cores.' },
      { id: 'fifty-cores', label: 'The number 50 in the percentage directly means 50 cores.' },
    ],
    correctImplicationId: 'raw-two-hundred',
    mentalModel: '50K × 4ms = 200 cores raw; ÷0.5 = 400.',
    hint: 'First solve at 100% utilisation. Then divide by the utilisation target.',
    walkthrough: ['50,000 × 0.004 CPU-seconds = 200 raw cores', '200 ÷ 0.5 = 400 provisioned cores', 'At the stated load, 200/400 = 50% utilisation'],
  },
  {
    id: 'compute-background-jobs',
    skillId: 'compute',
    title: 'Image processing workers',
    eyebrow: 'Workers · headroom',
    prompt: 'Two thousand jobs/second each consume 250 ms of CPU. Target 80% utilisation.',
    question: 'Estimate provisioned cores.',
    assumptions: ['Jobs are CPU-bound', 'Work can run in parallel'],
    formulaChoices: [
      { id: 'jobs-cpu-over-util', label: 'Jobs/s × CPU seconds/job ÷ utilisation' },
      { id: 'jobs-over-cpu-util', label: 'Jobs/s ÷ CPU seconds/job × utilisation' },
      { id: 'cpu-over-jobs', label: 'CPU seconds/job ÷ jobs/s' },
    ],
    correctFormulaId: 'jobs-cpu-over-util',
    answer: { baseValue: 625, dimension: 'compute', displayValue: 625, displayUnit: 'cores', tolerance: 0.02 },
    implicationChoices: [
      { id: 'queue-buffer', label: 'About 625 cores meets steady demand; a queue can absorb short arrival bursts.' },
      { id: 'two-cores', label: 'Two thousand jobs per second only requires two cores.' },
      { id: 'latency-cores', label: 'Wall-clock job latency alone determines the answer, regardless of CPU time.' },
    ],
    correctImplicationId: 'queue-buffer',
    mentalModel: '2K × 0.25 = 500 raw cores; 500 ÷ 0.8 = 625.',
    hint: '250 ms is one quarter of a CPU-second.',
    walkthrough: ['2,000 × 0.25 CPU-seconds = 500 raw cores', '500 ÷ 0.8 = 625 provisioned cores', 'Queueing helps with bursts but not sustained under-capacity'],
  },
  {
    id: 'compute-double-headroom',
    skillId: 'compute',
    title: 'A lightweight edge function',
    eyebrow: 'Edge · safety factor',
    prompt: 'An edge function handles 100,000 RPS at 1 ms CPU/request. Provision 2× raw demand.',
    question: 'How many cores should be provisioned?',
    assumptions: ['The 2× factor covers headroom and failures', 'CPU time is 1 ms/request'],
    formulaChoices: [
      { id: 'rps-ms-headroom', label: 'RPS × CPU ms/request ÷ 1,000 × headroom factor' },
      { id: 'rps-over-headroom', label: 'RPS ÷ headroom factor' },
      { id: 'ms-times-headroom', label: 'CPU ms/request × headroom factor' },
    ],
    correctFormulaId: 'rps-ms-headroom',
    answer: { baseValue: 200, dimension: 'compute', displayValue: 200, displayUnit: 'cores', tolerance: 0.01 },
    implicationChoices: [
      { id: 'raw-hundred', label: 'The function consumes 100 cores raw and is provisioned at 200 cores.' },
      { id: 'raw-two-hundred', label: 'Raw demand is already 200 cores before applying headroom.' },
      { id: 'one-core', label: 'One millisecond per request guarantees one core is sufficient.' },
    ],
    correctImplicationId: 'raw-hundred',
    mentalModel: '100K × 1ms ÷ 1K = 100 cores; ×2 = 200.',
    hint: 'Keep raw demand and the safety multiplier as separate steps.',
    walkthrough: ['100,000 × 1 ms = 100,000 CPU-ms/s', '÷1,000 = 100 raw cores', '100 × 2 = 200 provisioned cores'],
  },
]

export const scenariosBySkill = scenarios.reduce(
  (groups, scenario) => {
    groups[scenario.skillId].push(scenario)
    return groups
  },
  {
    foundations: [],
    load: [],
    storage: [],
    bandwidth: [],
    latency: [],
    compute: [],
  } as Record<SkillId, Scenario[]>,
)
